/**
 * ThyStreet
 * Thy Street APIs are completely RESTful and all our responses are returned in JSON.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@thystreet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DeviceTokenDto {
    /**
    * Device ID
    */
    'deviceId': string;
    /**
    * Set device token 
    */
    'token': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deviceId",
            "baseName": "deviceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceTokenDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

