/**
 * Thy Street
 * These are API's to easily manage your Thy Street device public pages. Thy Street APIs are completely RESTful and all our responses are returned in JSON.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: support@thystreet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderStatusDto {
    /**
    * Set order status
    */
    'status': OrderStatusDtoStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderStatusDtoStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderStatusDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OrderStatusDtoStatusEnum = "CONFIRMED" | "PENDING" | "COMPLETED" | "FAILED" ;

